name: mionder_mobile_get
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_svg: ^2.0.10+1
  path: ^1.9.0
  firebase_core: 2.31.0
  flutter: 
    sdk: flutter
  firebase_auth: ^4.19.5
  intl: ^0.19.0
  cloud_firestore: ^4.17.3
  calendar_date_picker2: ^1.0.2
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

