// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV04zjaKn4N1dkdhWzbuoGrAlW5C7CN9M',
    appId: '1:861343164583:web:6eca2acb5a83cabf1d1382',
    messagingSenderId: '861343164583',
    projectId: 'mionder-mobile',
    authDomain: 'mionder-mobile.firebaseapp.com',
    storageBucket: 'mionder-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQiuzMhbF_FagtM69hYIRhxwPu9IVj1U4',
    appId: '1:861343164583:android:ab54db13bf7aceb41d1382',
    messagingSenderId: '861343164583',
    projectId: 'mionder-mobile',
    storageBucket: 'mionder-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaEQWj8nzPi9yzjGlJd37VNrC324nAMow',
    appId: '1:861343164583:ios:48a39455e63e5e2a1d1382',
    messagingSenderId: '861343164583',
    projectId: 'mionder-mobile',
    storageBucket: 'mionder-mobile.appspot.com',
    iosBundleId: 'com.mionder.mionderMobileGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaEQWj8nzPi9yzjGlJd37VNrC324nAMow',
    appId: '1:861343164583:ios:48a39455e63e5e2a1d1382',
    messagingSenderId: '861343164583',
    projectId: 'mionder-mobile',
    storageBucket: 'mionder-mobile.appspot.com',
    iosBundleId: 'com.mionder.mionderMobileGet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV04zjaKn4N1dkdhWzbuoGrAlW5C7CN9M',
    appId: '1:861343164583:web:27bac163b2017ff31d1382',
    messagingSenderId: '861343164583',
    projectId: 'mionder-mobile',
    authDomain: 'mionder-mobile.firebaseapp.com',
    storageBucket: 'mionder-mobile.appspot.com',
  );
}
